Repository TeamRecorDream/RecorDream-Server, pull requests merged in 2022-07, with the labels that each got.

#3 Feature/1 setting
  .gitignore
  src/controllers/AuthController.ts
  src/controllers/NoticeController.ts
  src/controllers/RecordController.ts
  src/controllers/UserController.ts
  src/controllers/VoiceController.ts
  src/interfaces/auth/LoginDto.ts
  src/interfaces/auth/SignupDto.ts
  src/interfaces/common/JwtPayloadDto.ts
  src/interfaces/common/PostBaseResponseDto.ts
  src/interfaces/notice/NoticeCreateDto.ts
  src/interfaces/notice/NoticeInfo.ts
  src/interfaces/notice/NoticeResponseDto.ts
  src/interfaces/notice/NoticeUpdateDto.ts
  src/interfaces/record/RecordCreateDto.ts
  src/interfaces/record/RecordInfo.ts
  src/interfaces/record/RecordResponseDto.ts
  src/interfaces/record/RecordStorageResponseDto.ts
  src/interfaces/record/RecordUpdateDto.ts
  src/interfaces/user/UserInfo.ts
  src/interfaces/user/UserResponseDto.ts
  src/interfaces/user/UserUpdateDto.ts
  src/interfaces/voice/VoiceCreateDto.ts
  src/interfaces/voice/VoiceInfo.ts
  src/interfaces/voice/VoiceResponseDto.ts
  src/middleware/auth.ts
  src/models/Notice.ts
  src/models/Record.ts
  src/models/User.ts
  src/models/UserMocking.ts
  src/models/Voice.ts
  src/routes/AuthRouter.ts
  src/routes/NoticeRouter.ts
  src/routes/RecordRouter.ts
  src/routes/UserRouter.ts
  src/routes/VoiceRouter.ts
  src/services/AuthService.ts
  src/services/NoticeService.ts
  src/services/RecordService.ts
  src/services/UserService.ts
  src/services/VoiceService.ts
Labels: 🍯서경

#5 [Feat] 유저 닉네임 수정
  package-lock.json
  package.json
  src/controllers/UserController.ts
  src/controllers/index.ts
  src/index.ts
  src/interfaces/common/PostBaseResponseDto.ts
  src/interfaces/user/UserInfo.ts
  src/interfaces/user/UserNicknameUpdateDto.ts
  src/interfaces/user/UserUpdateDto.ts
  src/models/User.ts
  src/models/UserMocking.ts
  src/modules/reponseMessage.ts
  src/routes/UserRouter.ts
  src/routes/index.ts
  src/services/UserService.ts
  src/services/index.ts
  yarn.lock
Labels: 🍯서경

#17 [Add] appspec.yml 추가
  appspec.yml
Labels: 🍯서경

#28 [Fix] deploy.yml
  .github/workflows/deploy.yml
  package.json
Labels: 🦋시연

#23 Feature/16 post record
  .gitignore
  src/controllers/RecordController.ts
  src/controllers/index.ts
  src/interfaces/record/RecordCreateDto.ts
  src/interfaces/record/RecordInfo.ts
  src/models/Record.ts
  src/modules/reponseMessage.ts
  src/routes/RecordRouter.ts
  src/routes/index.ts
  src/services/RecordService.ts
  src/services/index.ts
  yarn.lock
Labels: 🐣서연

#32 Feature/7 post voice - POST&GET
  package-lock.json
  package.json
  src/config/index.ts
  src/config/multer.ts
  src/config/s3Config.ts
  src/controllers/VoiceController.ts
  src/controllers/index.ts
  src/interfaces/voice/VoiceCreateDto.ts
  src/interfaces/voice/VoiceInfo.ts
  src/interfaces/voice/VoiceResponseDto.ts
  src/loaders/db.ts
  src/models/Voice.ts
  src/modules/reponseMessage.ts
  src/routes/VoiceRouter.ts
  src/routes/index.ts
  src/services/VoiceService.ts
  src/services/index.ts
  yarn.lock
Labels: 👩‍💻 Server, 🦋시연

#35 Feature/11 notice toggle
  src/controllers/RecordController.ts
  src/controllers/UserController.ts
  src/controllers/VoiceController.ts
  src/modules/responseMessage.ts
  src/routes/UserRouter.ts
  src/services/UserService.ts
Labels: 🍯서경

#41 [Fix] 헤더에 잘못된 userId가 들어왔을 경우
  src/controllers/UserController.ts
  src/modules/responseMessage.ts
  src/services/UserService.ts
Labels: 🍯서경

#34 Feature/33 readme
  README.md
Labels: 🦋시연

#38 [Feat] Get Record
  README.md
  src/config/index.ts
  src/config/s3Config.ts
  src/controllers/RecordController.ts
  src/controllers/UserController.ts
  src/controllers/VoiceController.ts
  src/controllers/index.ts
  src/index.ts
  src/interfaces/record/RecordCreateDto.ts
  src/interfaces/record/RecordInfo.ts
  src/interfaces/record/RecordResponseDto.ts
  src/interfaces/voice/VoiceInfo.ts
  src/loaders/db.ts
  src/models/Record.ts
  src/models/User.ts
  src/models/UserMocking.ts
  src/modules/responseMessage.ts
  src/routes/RecordRouter.ts
  src/routes/UserRouter.ts
  src/routes/index.ts
  src/services/RecordService.ts
  src/services/UserService.ts
  src/services/VoiceService.ts
  src/services/index.ts
  yarn.lock
Labels: 👩‍💻 Server, 🦋시연

#45 Fix Feature/36 read record
  src/services/RecordService.ts
Labels: 🦋시연

#49 Feature/37 delete record
  src/controllers/RecordController.ts
  src/modules/responseMessage.ts
  src/routes/RecordRouter.ts
  src/services/RecordService.ts
Labels: 👩‍💻 Server, 🦋시연

#51 Feature/47 update record
  .github/workflows/deploy.yml
  src/controllers/RecordController.ts
  src/controllers/VoiceController.ts
  src/interfaces/record/RecordInfo.ts
  src/interfaces/record/RecordResponseDto.ts
  src/interfaces/record/RecordUpdateDto.ts
  src/models/Record.ts
  src/modules/responseMessage.ts
  src/routes/RecordRouter.ts
  src/services/RecordService.ts
Labels: 👩‍💻 Server, 🦋시연

#53 Feature/44 get list home
  src/controllers/RecordController.ts
  src/interfaces/record/RecordInfo.ts
  src/interfaces/record/RecordListResponseDto.ts
  src/modules/responseMessage.ts
  src/routes/RecordRouter.ts
  src/services/RecordService.ts
Labels: 🐣서연

#50 Feature/39 post notice
  .github/workflows/deploy.yml
  .gitignore
  package-lock.json
  package.json
  src/config/index.ts
  src/controllers/NoticeController.ts
  src/controllers/index.ts
  src/interfaces/notice/NoticeBaseDto.ts
  src/interfaces/notice/NoticeCreateDto.ts
  src/interfaces/notice/NoticeInfo.ts
  src/interfaces/notice/NoticeResponseDto.ts
  src/interfaces/notice/NoticeUpdateDto.ts
  src/jobs/agenda.ts
  src/loaders/db.ts
  src/models/Notice.ts
  src/models/Voice.ts
  src/modules/responseMessage.ts
  src/routes/NoticeRouter.ts
  src/routes/index.ts
  src/services/NoticeService.ts
  src/services/RecordService.ts
  src/services/index.ts
  tsconfig.json
  yarn.lock
Labels: 🍯서경

#54 Feature/52 update notice
  src/controllers/NoticeController.ts
  src/interfaces/notice/NoticeResponseDto.ts
  src/loaders/db.ts
  src/models/Notice.ts
  src/modules/responseMessage.ts
  src/routes/NoticeRouter.ts
  src/services/NoticeService.ts
  src/services/UserService.ts
Labels: 🍯서경

#57 Feature/55 fcm token refresh
  .github/workflows/deploy.yml
  src/controllers/UserController.ts
  src/interfaces/user/FcmTokenUpdateDto.ts
  src/modules/responseMessage.ts
  src/routes/UserRouter.ts
  src/services/UserService.ts
Labels: 🍯서경

#61 Feature/48 fix voice
  README.md
  src/config/multer.ts
  src/config/s3Config.ts
  src/controllers/RecordController.ts
  src/controllers/VoiceController.ts
  src/index.ts
  src/interfaces/record/RecordCreateDto.ts
  src/interfaces/record/RecordInfo.ts
  src/interfaces/record/RecordListResponseDto.ts
  src/interfaces/record/RecordResponseDto.ts
  src/interfaces/voice/VoiceInfo.ts
  src/interfaces/voice/VoiceResponseDto.ts
  src/models/Record.ts
  src/models/User.ts
  src/models/UserMocking.ts
  src/models/Voice.ts
  src/models/VoiceMocking.ts
  src/routes/RecordRouter.ts
  src/routes/VoiceRouter.ts
  src/services/VoiceService.ts
  yarn.lock
Labels: 👩‍💻 Server, 🦋시연

#59 Feature/46 get list storage
  README.md
  src/controllers/RecordController.ts
  src/interfaces/record/RecordStorageResponseDto.ts
  src/models/Notice.ts
  src/modules/responseMessage.ts
  src/routes/RecordRouter.ts
  src/services/RecordService.ts
Labels: 🐣서연

#64 Feature/62 get record by search
  README.md
  src/controllers/RecordController.ts
  src/modules/responseMessage.ts
  src/routes/RecordRouter.ts
  src/services/RecordService.ts
Labels: 🐣서연

#68 Fix/67 get user time
  src/interfaces/auth/LoginDto.ts
  src/interfaces/auth/SignupDto.ts
  src/interfaces/common/JwtPayloadDto.ts
  src/interfaces/user/UserInfo.ts
  src/interfaces/user/UserResponseDto.ts
  src/models/User.ts
  src/routes/NoticeRouter.ts
  src/services/RecordService.ts
Labels: 🍯서경

#71 [Fix] Notice 코드 검토
  src/controllers/NoticeController.ts
  src/interfaces/user/UserUpdateDto.ts
  src/services/NoticeService.ts
  src/services/RecordService.ts
Labels: 🐣서연

#74 Fix/73 fix record model
  src/controllers/RecordController.ts
  src/models/Record.ts
  src/modules/responseMessage.ts
  src/services/RecordService.ts
Labels: 🐣서연

#76 [Chore] package.json
  package.json
Labels: 🍯서경

#81 Feature/63 test environment
  jest.config.js
  package.json
  src/app.ts
  src/routes/RecordRouter.ts
  src/tests/data.json
  src/tests/record.test.ts
  test-teardown-globals.ts
  yarn.lock
Labels: 👩‍💻 Server, 🦋시연

#85 Fix/82 record review
  src/controllers/RecordController.ts
  src/interfaces/record/RecordCreateDto.ts
  src/models/Record.ts
  src/services/RecordService.ts
Labels: 🦋시연, 🐣서연

#86 Fix/80 push alarm
  src/controllers/NoticeController.ts
  src/controllers/UserController.ts
  src/interfaces/notice/NoticeBaseDto.ts
  src/interfaces/notice/NoticeInfo.ts
  src/interfaces/user/FcmTokenUpdateDto.ts
  src/interfaces/user/UserAlarmDto.ts
  src/interfaces/user/UserResponseDto.ts
  src/models/Notice.ts
  src/models/User.ts
  src/modules/pushMessage.ts
  src/modules/responseMessage.ts
  src/services/NoticeService.ts
  src/services/UserService.ts
Labels: 🍯서경

#89 Feature/83 test siyeon
  src/controllers/RecordController.ts
  src/interfaces/record/RecordCreateDto.ts
  src/interfaces/record/RecordUpdateDto.ts
  src/modules/responseMessage.ts
  src/services/RecordService.ts
  src/tests/data.json
  src/tests/record.test.ts
  src/tests/voice.test.ts
Labels: 🦋시연

#90 Feature/83 test siyeon
  src/tests/record.test.ts
Labels: 👩‍💻 Server, 🦋시연

#95 Feature/93 nickname limit
  src/controllers/UserController.ts
  src/interfaces/user/FcmTokenUpdateDto.ts
  src/routes/UserRouter.ts
  src/services/UserService.ts
Labels: 🍯서경

#98 [Fix] 전체 로직 fix
  src/controllers/UserController.ts
  src/interfaces/notice/NoticeBaseDto.ts
  src/interfaces/notice/NoticeInfo.ts
  src/interfaces/user/FcmTokenUpdateDto.ts
  src/models/Notice.ts
  src/models/User.ts
  src/routes/UserRouter.ts
  src/services/NoticeService.ts
  src/services/UserService.ts
Labels: 🍯서경

#101 Feature/99 debug husky
  .husky/pre-commit
  .husky/pre-push
  package.json
  yarn.lock
Labels: 🦋시연

#102 [Fix] 푸시알림 시간 설정, 수정
  src/controllers/NoticeController.ts
  src/modules/responseMessage.ts
  src/routes/NoticeRouter.ts
  src/services/NoticeService.ts
Labels: 🍯서경

#106 Feature/104 slack webhook
  package.json
  src/config/index.ts
  src/controllers/NoticeController.ts
  src/controllers/RecordController.ts
  src/controllers/UserController.ts
  src/controllers/VoiceController.ts
  src/modules/returnToSlackMessage.ts
  src/modules/slackAPI.ts
  yarn.lock
Labels: 🦋시연

#110 [Fix] User
  package-lock.json
  package.json
  src/controllers/UserController.ts
  src/models/Notice.ts
  src/routes/UserRouter.ts
  src/services/NoticeService.ts
  src/services/UserService.ts
  yarn.lock
Labels: 🍯서경

#111 [Fix] 날짜 한국어
  src/services/UserService.ts
Labels: 🍯서경

#114 [Fix] 푸시알림 글로벌 시간
  src/services/UserService.ts
Labels: 🍯서경

#115 [Fix] ec2 서버시간
  src/services/UserService.ts
Labels: 🍯서경

#117 Feature/116 record get test ver2
  src/services/RecordService.ts
  src/tests/getRecordList.test.ts
  src/tests/getRecordStorage.test.ts
  src/tests/getRecordsBySearch.test.ts
Labels: 🐣서연

#119 [Fix] 푸시알림 에러 핸들링
  src/services/NoticeService.ts
  src/services/UserService.ts
Labels: 🍯서경

#122 Feature/112 report
  .husky/pre-commit
  .huskyrc
  src/config/index.ts
  src/modules/returnToSlackMessage.ts
  src/services/RecordService.ts
  src/tests/deleteRecord.test.ts
  src/tests/getRecord.test.ts
  src/tests/getUser.test.ts
  src/tests/getVoice.test.ts
  src/tests/patchRecord.test.ts
  src/tests/postRecord.test.ts
  src/tests/postVoice.test.ts
  src/tests/putUser.test.ts
  src/tests/record.test.ts
  yarn.lock
Labels: 🦋시연

#121 Feature/118 record get test ver3
  src/tests/getRecordList.test.ts
  src/tests/getRecordStorage.test.ts
Labels: 🐣서연

#126 [Fix] 푸시알림 로직
  src/controllers/NoticeController.ts
  src/routes/NoticeRouter.ts
  src/services/NoticeService.ts
  src/services/UserService.ts
Labels: 🍯서경

#127 [Fix] 푸시알림 에러 핸들링
  src/controllers/NoticeController.ts
  src/services/NoticeService.ts
Labels: 🍯서경

#128 [Fix] 에러 핸들링
  src/controllers/NoticeController.ts
  src/services/NoticeService.ts
  src/services/UserService.ts
Labels: 🍯서경

#129 [Fix] 에러
  src/controllers/NoticeController.ts
  src/services/NoticeService.ts
  src/services/UserService.ts
Labels: 🍯서경

#130 [Fix] 꿈기록 작성 날짜
  src/models/Record.ts
  src/services/RecordService.ts
Labels: 🍯서경

#131 [Fix] date null 불가
  src/models/Record.ts
  src/services/RecordService.ts
Labels: 🍯서경

#72 [Chore] deploy 파일 수정
  .github/workflows/deploy.yml
Labels: 🍯서경

#133 [Add] 배포 자동화 작업
  .github/workflows/deploy.yml
  src/modules/responseMessage.ts
Labels: 🍯서경

#135 [Chore] 경로 수정
  appspec.yml
Labels: 🍯서경

#136 Feat/132 cd
  .github/workflows/deploy.yml
  scripts/after-deploy.sh
  src/modules/responseMessage.ts
Labels: 🍯서경

#137 [Chore] CD 반영 여부 test
  src/modules/responseMessage.ts
Labels: 🍯서경

#138 [Chore] dist 빌드 경로 수정
  scripts/after-deploy.sh
Labels: 🍯서경

#140 [Add] deploy 작업 추가
  .github/workflows/deploy.yml
Labels: 🍯서경

#141 [Chore] 경로 수정
  scripts/after-deploy.sh
Labels: 🍯서경

#142 [Chore] CD test
  src/modules/responseMessage.ts
Labels: 🍯서경

#143 [Add] 경로 추가
  appspec.yml
  scripts/after-deploy.sh
Labels: 🍯서경

#144 [Del] 경로
  appspec.yml
  scripts/after-deploy.sh
Labels: 🍯서경
