Repository TeamRecorDream/RecorDream-Server, pull requests merged in 2022-11, with the labels that each got.

#170 [Refactor] 회원 로그아웃
  src/controllers/AuthController.ts
  src/services/AuthService.ts
Labels: 👩‍💻 Server, Fix, 🍯서경

#173 [Fix] 푸시알림 시간 설정
  package-lock.json
  package.json
  src/controllers/NoticeController.ts
  src/controllers/UserController.ts
  src/interfaces/notice/NoticeBaseDto.ts
  src/interfaces/notice/NoticeInfo.ts
  src/interfaces/user/UserInfo.ts
  src/interfaces/user/UserNoticePostDto.ts
  src/models/Notice.ts
  src/models/User.ts
  src/modules/exceptionMessage.ts
  src/modules/responseMessage.ts
  src/routes/NoticeRouter.ts
  src/routes/UserRouter.ts
  src/services/AuthService.ts
  src/services/NoticeService.ts
  src/services/UserService.ts
  yarn.lock
Labels: enhancement, 👩‍💻 Server, 🍯서경

#175 [Fix] toggle off
  src/controllers/NoticeController.ts
  src/controllers/UserController.ts
  src/routes/NoticeRouter.ts
  src/routes/UserRouter.ts
  src/services/NoticeService.ts
  src/services/UserService.ts
Labels: 👩‍💻 Server, Fix, 🍯서경

#180 [Refactor] 회원정보 조회
  src/controllers/UserController.ts
  src/interfaces/user/UserResponseDto.ts
  src/routes/UserRouter.ts
  src/services/UserService.ts
Labels: enhancement, 👩‍💻 Server, 🍯서경

#183 [Refactor] 회원삭제 body userId -> accesstoken
  src/controllers/UserController.ts
  src/services/UserService.ts
Labels: enhancement, 👩‍💻 Server, 🍯서경

#172 Feature/163 voice refactor
  package.json
  src/controllers/VoiceController.ts
  src/interfaces/voice/VoiceInfo.ts
  src/interfaces/voice/VoiceResponseDto.ts
  src/interfaces/voice/VoiceUploadDto.ts
  src/models/Voice.ts
  src/modules/responseMessage.ts
  src/routes/VoiceRouter.ts
  src/services/RecordService.ts
  src/services/VoiceService.ts
  yarn.lock
Labels: enhancement, 👩‍💻 Server, 🦋시연

#186 [Refactor] fcmtoken refresh
  src/controllers/AuthController.ts
  src/controllers/UserController.ts
  src/interfaces/user/FcmTokenUpdateDto.ts
  src/modules/exceptionMessage.ts
  src/modules/responseMessage.ts
  src/services/UserService.ts
Labels: enhancement, 👩‍💻 Server, 🍯서경

#189 [Feat] nickname length
  src/interfaces/user/UserInfo.ts
  src/models/User.ts
  src/services/AuthService.ts
Labels: enhancement, 👩‍💻 Server, 🍯서경

#191 Feature/185 get record re
  src/controllers/RecordController.ts
  src/interfaces/record/RecordResponseDto.ts
  src/interfaces/voice/VoiceResponseInRecordDto.ts
  src/routes/RecordRouter.ts
  src/services/RecordService.ts
Labels: enhancement, 👩‍💻 Server, 🦋시연

#192 [Fix] push alarm
  src/controllers/UserController.ts
  src/services/UserService.ts
Labels: 👩‍💻 Server, Fix, 🍯서경

#197 [Refactor] storage list, 보관함 뷰 꿈기록 조회
  src/controllers/RecordController.ts
  src/interfaces/record/RecordInfo.ts
  src/interfaces/record/RecordStorageResponseDto.ts
  src/modules/responseMessage.ts
  src/routes/RecordRouter.ts
  src/services/RecordService.ts
Labels: enhancement, 👩‍💻 Server, 🍯서경

#199 [Chore] build 오류 해결
  src/modules/responseMessage.ts
Labels: 👩‍💻 Server, Fix, 🍯서경

#201 [Fix] 감정 디폴트 6, 색깔 삭제, 날짜 형식 400
  src/controllers/RecordController.ts
  src/modules/responseMessage.ts
  src/routes/RecordRouter.ts
  src/services/RecordService.ts
  yarn.lock
Labels: 👩‍💻 Server, Fix, 🦋시연

#202 Feature/194 patch record re
  src/controllers/RecordController.ts
  src/interfaces/record/RecordUpdateDto.ts
  src/modules/exceptionMessage.ts
  src/modules/responseMessage.ts
  src/routes/RecordRouter.ts
  src/services/RecordService.ts
Labels: enhancement, 👩‍💻 Server, 🦋시연

#204 Fix/203 voice auth
  src/controllers/VoiceController.ts
  src/routes/VoiceRouter.ts
Labels: 👩‍💻 Server, Fix, 🦋시연

#207 [Chore] 시간 수정 시 다시 작업 start
  src/services/UserService.ts
Labels: 👩‍💻 Server, Fix, 🍯서경

#209 [Chore] 예약 이름 다르게 하여 job 구분
  src/services/UserService.ts
Labels: 👩‍💻 Server, Fix, 🍯서경
