Repository TeamRecorDream/RecorDream-Server, pull requests merged in 2022-10, with the labels that each got.

#148 Feature/147 kakao
  src/config/index.ts
  src/controllers/AuthController.ts
  src/controllers/index.ts
  src/interfaces/auth/AuthResponseDto.ts
  src/interfaces/common/JwtPayloadInfo.ts
  src/interfaces/user/UserInfo.ts
  src/middleware/auth.ts
  src/models/User.ts
  src/modules/jwtHandler.ts
  src/modules/responseMessage.ts
  src/routes/AuthRouter.ts
  src/routes/index.ts
  src/services/AuthService.ts
  src/services/UserService.ts
  src/services/index.ts
Labels: 👩‍💻 Server, 🍯서경

#150 Feature/149 actoken reissue
  .github/workflows/deploy.yml
  src/modules/jwtHandler.ts
Labels: 👩‍💻 Server, 🍯서경

#151 [Add] 한 유저가 여러 기기로 로그인한 경우 fcmToken 추가저장
  src/services/AuthService.ts
Labels: 👩‍💻 Server, 🍯서경

#152 Feature/149 actoken reissue
  src/controllers/AuthController.ts
  src/interfaces/user/UserInfo.ts
  src/middleware/auth.ts
  src/modules/exceptionMessage.ts
  src/modules/jwtHandler.ts
  src/modules/responseMessage.ts
  src/routes/AuthRouter.ts
  src/services/AuthService.ts
Labels: 👩‍💻 Server, 🍯서경

#155 [Feat] 애플 로그인, 회원가입
  src/controllers/AuthController.ts
  src/interfaces/user/UserInfo.ts
  src/models/User.ts
  src/services/AuthService.ts
Labels: 👩‍💻 Server, 🍯서경

#158 Feat/157 logout
  src/controllers/AuthController.ts
  src/interfaces/auth/AuthLogoutDto.ts
  src/interfaces/auth/AuthResponseDto.ts
  src/middleware/auth.ts
  src/modules/exceptionMessage.ts
  src/modules/responseMessage.ts
  src/routes/AuthRouter.ts
  src/services/AuthService.ts
Labels: enhancement, 🍯서경

#156 Feature/154 use swagger
  .husky/pre-commit
  build/swagger.yaml
  package-lock.json
  package.json
  src/app.ts
  src/index.ts
  src/swagger/components/parameters/listFilter.param.yaml
  src/swagger/components/parameters/recordId.param.yaml
  src/swagger/components/parameters/searchKeyword.param.yaml
  src/swagger/components/responses/global/badRequest.res.yaml
  src/swagger/components/responses/global/internalServerError.res.yaml
  src/swagger/components/responses/global/noContent.res.yaml
  src/swagger/components/responses/global/notFound.res.yaml
  src/swagger/components/responses/global/nullValue.res.yaml
  src/swagger/components/responses/records/createRecordFail.res.yaml
  src/swagger/components/responses/records/createRecordSuccess.res.yaml
  src/swagger/components/responses/records/readRecordListSuccess.res.yaml
  src/swagger/components/responses/records/readRecordStorageSuccess.res.yaml
  src/swagger/components/responses/records/readRecordSuccess.res.yaml
  src/swagger/components/responses/records/searchRecordSuccess.res.yaml
  src/swagger/components/responses/records/updateRecordFail.res.yaml
  src/swagger/components/responses/records/updateRecordSuccess.res.yaml
  src/swagger/components/schemas/error/error.schema.yaml
  src/swagger/components/schemas/record/new-record.schema.yaml
  src/swagger/components/schemas/record/record.schema.yaml
  src/swagger/components/schemas/success/id.schema.yaml
  src/swagger/components/schemas/success/success.schema.yaml
  src/swagger/openapi.yaml
  src/swagger/paths/records/record-by-id.openapi.yaml
  src/swagger/paths/records/record-storage-list.openapi.yaml
  src/swagger/paths/records/record-storage-search.openapi.yaml
  src/swagger/paths/records/record.openapi.yaml
  yarn.lock
Labels: 🦋시연

#160 [Feat] 회원 탈퇴
  package.json
  src/controllers/UserController.ts
  src/modules/responseMessage.ts
  src/routes/UserRouter.ts
  src/services/UserService.ts
  yarn.lock
Labels: 👩‍💻 Server, 🍯서경

#166 [Fix] Toggle OFF
  src/controllers/NoticeController.ts
  src/controllers/UserController.ts
  src/interfaces/notice/NoticeBaseDto.ts
  src/interfaces/notice/NoticeInfo.ts
  src/interfaces/notice/NoticeOffDto.ts
  src/interfaces/user/UserAlarmDto.ts
  src/interfaces/user/UserInfo.ts
  src/models/Notice.ts
  src/models/User.ts
  src/modules/responseMessage.ts
  src/routes/NoticeRouter.ts
  src/routes/UserRouter.ts
  src/services/AuthService.ts
  src/services/NoticeService.ts
  src/services/UserService.ts
Labels: 👩‍💻 Server, Fix, 🍯서경

#168 Fix/167 update nickname
  src/controllers/UserController.ts
  src/middleware/auth.ts
  src/modules/responseMessage.ts
  src/routes/UserRouter.ts
  src/services/AuthService.ts
  src/services/UserService.ts
Labels: 👩‍💻 Server, Fix, 🍯서경
