Repository TeamRecorDream/RecorDream-Server, pull requests merged in 2022-12, with the labels that each got.

#211 Feature/210 search record re
  src/controllers/RecordController.ts
  src/interfaces/record/RecordInfo.ts
  src/routes/RecordRouter.ts
  src/services/RecordService.ts
Labels: enhancement, 👩‍💻 Server, 🦋시연

#213 [Refactor] delete emotion arr
  src/interfaces/user/UserInfo.ts
  src/models/User.ts
  src/routes/RecordRouter.ts
  src/services/RecordService.ts
Labels: enhancement, 👩‍💻 Server, 🍯서경

#216 [Chore] 401 -> 403
  src/controllers/AuthController.ts
Labels: enhancement, 👩‍💻 Server, 🍯서경

#218 [Fix] apple login & toggle on/off
  src/controllers/UserController.ts
  src/interfaces/user/ToggleChangeDto.ts
  src/modules/responseMessage.ts
  src/services/AuthService.ts
  src/services/UserService.ts
Labels: 👩‍💻 Server, Fix, 🍯서경

#220 [Fix] push alarm server restart
  src/loaders/agenda.ts
  src/loaders/db.ts
  src/services/UserService.ts
  src/services/agenda.ts
Labels: 👩‍💻 Server, Fix, 🍯서경

#222 [Add] search in title
  src/services/RecordService.ts
Labels: 👩‍💻 Server, Fix, 🦋시연

#223 [Chore] push alarm
  src/loaders/db.ts
  src/services/UserService.ts
Labels: 👩‍💻 Server, Fix, 🍯서경

#225 [Del] usermocking, voicemocking
  src/models/UserMocking.ts
  src/models/VoiceMocking.ts
Labels: enhancement, 👩‍💻 Server, 🍯서경
