Repository TeamRecorDream/RecorDream-Server, pull requests merged in 2023-01, with the labels that each got.

#227 [Feat] auth swagger 연결
  build/swagger.yaml
  src/swagger/components/parameters/accessToken.param.yaml
  src/swagger/components/parameters/refreshToken.param.yaml
  src/swagger/components/responses/auth/logoutSuccess.res.yaml
  src/swagger/components/responses/auth/nullValueToken.res.yaml
  src/swagger/components/responses/auth/refreshTokenSuccess.res.yaml
  src/swagger/components/responses/auth/validToken.res.yaml
  src/swagger/components/schemas/auth/auth.schema.yaml
  src/swagger/openapi.yaml
  src/swagger/paths/auth/auth-login.openapi.yaml
  src/swagger/paths/auth/auth-logout.openapi.yaml
  src/swagger/paths/auth/auth-token.openapi.yaml
Labels: enhancement, 👩‍💻 Server, 🍯서경

#231 [Chore] 보관함뷰 특정유저 기록만 불러오기
  src/services/RecordService.ts
Labels: 👩‍💻 Server, Fix, 🍯서경

#232 [Fix] logout&lockedAt
  src/loaders/db.ts
  src/services/AuthService.ts
Labels: 👩‍💻 Server, Fix, 🍯서경

#234 undefined 로직 추가
  src/services/RecordService.ts
Labels: 👩‍💻 Server, Fix, 🦋시연

#236 [Feat] storage&user delete
  build/swagger.yaml
  src/controllers/RecordController.ts
  src/controllers/UserController.ts
  src/middleware/auth.ts
  src/models/User.ts
  src/services/RecordService.ts
  src/services/UserService.ts
  src/swagger/components/responses/global/noUser.res.yaml
  src/swagger/paths/records/record-storage-list.openapi.yaml
  src/swagger/paths/user/user.openapi.yaml
Labels: enhancement, 👩‍💻 Server, 🍯서경

#237 [Feat] 회원 탈퇴 시, 녹음 삭제 및 푸시알림 예약 취소
  src/interfaces/auth/AuthResponseDto.ts
  src/interfaces/user/UserResponseDto.ts
  src/services/UserService.ts
Labels: enhancement, 👩‍💻 Server, 🍯서경

#239 [Fix] delete voice with record
  src/services/RecordService.ts
Labels: 👩‍💻 Server, Fix, 🦋시연

#241 [Fix] 소셜로그인 400
  src/controllers/AuthController.ts
Labels: 👩‍💻 Server, Fix, 🍯서경

#242 [Add] kakaoToken="" 일때도 400, 홈뷰&보관함뷰 녹음여부 추가
  src/controllers/AuthController.ts
  src/interfaces/record/RecordInfo.ts
  src/services/RecordService.ts
Labels: enhancement, 👩‍💻 Server, 🍯서경

#244 [Chore] accessToken 만료 시, 401->406으로 변경
  src/middleware/auth.ts
  src/modules/statusCode.ts
Labels: enhancement, 👩‍💻 Server, 🍯서경

#246 [Add] 소셜 로그인 및 회원가입 response에 userId 추가
  src/interfaces/auth/AuthResponseDto.ts
  src/services/AuthService.ts
Labels: enhancement, 👩‍💻 Server, 🍯서경

#248 [Feat] get app version
  .github/PULL_REQUEST_TEMPLATE.md
  src/controllers/VersionController.ts
  src/controllers/index.ts
  src/interfaces/version/VersionInfo.ts
  src/models/Version.ts
  src/modules/responseMessage.ts
  src/routes/VersionRouter.ts
  src/routes/index.ts
  src/services/VersionService.ts
  src/services/index.ts
Labels: enhancement, 👩‍💻 Server, 🍯서경
